[workspace]
members = ["libs", "cli", "mosh", "terminal"]

[package]
name = "termio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libs = { path = "libs/" }
cli = { path = "cli/" }