[package]
name = "terminal"
version = "0.1.0"
edition = "2021"

[dependencies]
tmui = { git = "https://github.com/toocol/tmui" }

libs = { path = "../libs/" }
termulator = { path = "../termulator/" }

log = "0.4"
log4rs = "1.1.1"